2021-04-26 07:10:40,600 INFO    MainThread:2058 [wandb_setup.py:_flush():69] setting env: {}
2021-04-26 07:10:40,600 INFO    MainThread:2058 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-26 07:10:40,600 INFO    MainThread:2058 [wandb_init.py:_log_setup():336] Logging user logs to /home/datasci/CA-MTL/wandb/run-20210426_071040-3h0o33dt/logs/debug.log
2021-04-26 07:10:40,600 INFO    MainThread:2058 [wandb_init.py:_log_setup():337] Logging internal logs to /home/datasci/CA-MTL/wandb/run-20210426_071040-3h0o33dt/logs/debug-internal.log
2021-04-26 07:10:40,600 INFO    MainThread:2058 [wandb_init.py:init():369] calling init triggers
2021-04-26 07:10:40,600 INFO    MainThread:2058 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'output_dir': '/hub/CA-MTL/data/SCORED', 'overwrite_output_dir': False, 'do_train': False, 'do_eval': False, 'do_predict': True, 'evaluate_during_training': False, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 8, 'per_gpu_train_batch_size': None, 'per_gpu_eval_batch_size': None, 'gradient_accumulation_steps': 1, 'learning_rate': 5e-05, 'weight_decay': 0.0, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'num_train_epochs': 3.0, 'max_steps': -1, 'warmup_steps': 0, 'logging_dir': None, 'logging_first_step': False, 'logging_steps': 500, 'save_steps': 500, 'save_total_limit': None, 'no_cuda': False, 'seed': 42, 'fp16': False, 'fp16_opt_level': 'O1', 'local_rank': -1, 'tpu_num_cores': None, 'tpu_metrics_debug': False, 'use_mt_uncertainty': False, 'uniform_mt_sampling': False, 'percent_of_max_data_size': 1.0, '__cached__setup_devices': (device(type='cuda'), 1)}
2021-04-26 07:10:40,601 INFO    MainThread:2058 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 2vwtozct
2021-04-26 07:10:40,602 INFO    MainThread:2058 [wandb_run.py:finish():1167] finishing run heatxg/huggingface/2vwtozct
2021-04-26 07:10:40,602 INFO    MainThread:2058 [jupyter.py:save_history():320] not saving jupyter history
2021-04-26 07:10:40,602 INFO    MainThread:2058 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-04-26 07:10:40,602 INFO    MainThread:2058 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-04-26 07:10:40,602 INFO    MainThread:2058 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-04-26 07:10:40,602 INFO    MainThread:2058 [wandb_run.py:_restore():1466] restore
2021-04-26 07:10:40,933 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 831
  total_bytes: 831
}

2021-04-26 07:10:41,305 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 831
  total_bytes: 3121
}

2021-04-26 07:10:41,620 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4896
  total_bytes: 5046
}

2021-04-26 07:10:41,722 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4896
  total_bytes: 5046
}

2021-04-26 07:10:41,823 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4896
  total_bytes: 5046
}

2021-04-26 07:10:41,925 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4896
  total_bytes: 5046
}

2021-04-26 07:10:42,026 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4896
  total_bytes: 5046
}

2021-04-26 07:10:42,127 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5046
  total_bytes: 5046
}

2021-04-26 07:10:42,229 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5046
  total_bytes: 5046
}

2021-04-26 07:10:42,330 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5046
  total_bytes: 5046
}

2021-04-26 07:10:42,431 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5046
  total_bytes: 5046
}

2021-04-26 07:10:42,532 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5046
  total_bytes: 5046
}

2021-04-26 07:10:42,634 INFO    MainThread:2058 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5046
  total_bytes: 5046
}

2021-04-26 07:10:43,716 INFO    MainThread:2058 [wandb_run.py:_show_files():1838] logging synced files
2021-04-26 07:10:43,719 INFO    MainThread:2058 [wandb_init.py:init():418] starting backend
2021-04-26 07:10:43,719 INFO    MainThread:2058 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-26 07:10:43,721 INFO    MainThread:2058 [backend.py:ensure_launched():123] starting backend process...
2021-04-26 07:10:43,747 INFO    MainThread:2058 [backend.py:ensure_launched():128] started backend process with pid: 3537
2021-04-26 07:10:43,748 INFO    MainThread:2058 [wandb_init.py:init():423] backend started and connected
2021-04-26 07:10:43,761 INFO    MainThread:2058 [wandb_init.py:init():463] updated telemetry
2021-04-26 07:10:43,762 INFO    MainThread:2058 [wandb_init.py:init():482] communicating current version
2021-04-26 07:10:48,763 INFO    MainThread:2058 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-26 07:11:08,646 INFO    MainThread:2058 [wandb_init.py:init():520] starting run threads in backend
2021-04-26 07:11:09,032 INFO    MainThread:2058 [wandb_run.py:_console_start():1524] atexit reg
2021-04-26 07:11:09,032 INFO    MainThread:2058 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-04-26 07:11:09,032 INFO    MainThread:2058 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-04-26 07:11:09,032 INFO    MainThread:2058 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-26 07:11:09,033 INFO    MainThread:2058 [wandb_init.py:init():544] run started, returning control to user process
2021-04-26 07:11:09,033 INFO    MainThread:2058 [wandb_watch.py:watch():39] Watching
2021-04-26 07:12:21,022 INFO    MainThread:2058 [wandb_setup.py:_flush():69] setting env: {}
2021-04-26 07:12:21,022 INFO    MainThread:2058 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-26 07:12:21,022 INFO    MainThread:2058 [wandb_init.py:_log_setup():336] Logging user logs to /home/datasci/CA-MTL/wandb/run-20210426_071220-2aydq4nq/logs/debug.log
2021-04-26 07:12:21,022 INFO    MainThread:2058 [wandb_init.py:_log_setup():337] Logging internal logs to /home/datasci/CA-MTL/wandb/run-20210426_071220-2aydq4nq/logs/debug-internal.log
2021-04-26 07:12:21,023 INFO    MainThread:2058 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9350b87850>
2021-04-26 07:12:21,023 INFO    MainThread:2058 [wandb_init.py:init():369] calling init triggers
2021-04-26 07:12:21,023 INFO    MainThread:2058 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {'output_dir': '/hub/CA-MTL/data/SCORED', 'overwrite_output_dir': False, 'do_train': False, 'do_eval': False, 'do_predict': True, 'evaluate_during_training': False, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 8, 'per_gpu_train_batch_size': None, 'per_gpu_eval_batch_size': None, 'gradient_accumulation_steps': 1, 'learning_rate': 5e-05, 'weight_decay': 0.0, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'num_train_epochs': 3.0, 'max_steps': -1, 'warmup_steps': 0, 'logging_dir': None, 'logging_first_step': False, 'logging_steps': 500, 'save_steps': 500, 'save_total_limit': None, 'no_cuda': False, 'seed': 42, 'fp16': False, 'fp16_opt_level': 'O1', 'local_rank': -1, 'tpu_num_cores': None, 'tpu_metrics_debug': False, 'use_mt_uncertainty': False, 'uniform_mt_sampling': False, 'percent_of_max_data_size': 1.0, '__cached__setup_devices': (device(type='cuda'), 1)}
2021-04-26 07:12:21,023 INFO    MainThread:2058 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 3h0o33dt
2021-04-26 07:12:21,024 INFO    MainThread:2058 [wandb_run.py:finish():1167] finishing run heatxg/huggingface/3h0o33dt
